places_to_visit = ["neighbors", "dog park", "restaurant at the end of the universe", "supermarket"]
print("The list:")
print(places_to_visit)
print("The list sorted:")
print(sorted(places_to_visit))
print("The list:")
print(places_to_visit)
print("The list reverse sorted:")
print(sorted(places_to_visit, reverse=True))
print("The list:")
print(places_to_visit)
print("The list reversed:")
places_to_visit.reverse()
print(places_to_visit)
print("The list reversed back:")
places_to_visit.reverse()
print(places_to_visit)
print("The list sorted:")
places_to_visit.sort()
print(places_to_visit)
print("The list reverse sorted:")
places_to_visit.sort(reverse=True)
print(places_to_visit)